import owner from "./components/assets/images/Ellipse 7.svg";
import dot from "./components/assets/icons/•.svg"

export const dataBase = [
  {
    id: 1,
    video:
      "https://www.columbiacollege.ca/wp-content/uploads/2019/05/Music.png",
    owner: owner,
    title: "Musical Instruments",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "music",
  },
  {
    id: 2,
    video:
      "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/4f995dde6b43fbe45bab9336476a66df17cc83270f06bc5e73492d21edcf7bef._RI_TTW_.jpg",
    owner: owner ,
    title: "Tom & Jerry",
    channel: "LOREM IPSUM",
    views: "1.6K views",
    dot: dot,
    time: "10 days ago",
    category: "cartoon",
  },
  {
    id: 3,
    video:
      "https://www.usmagazine.com/wp-content/uploads/1428049615_mcdsaha_ec188_h_the-fast-the-furious-zoom.jpg?crop=0px%2C215px%2C1280px%2C673px&resize=1200%2C630&quality=40&strip=all",
    owner:  owner ,
    title: "Fast and Furious 10",
    channel: "LOREM IPSUM",
    views: "1.4K views",
    dot: dot,
    time: "10 days ago",
    category: "movie",
  },
  {
    id: 4,
    video:
      "https://daily.jstor.org/wp-content/uploads/2023/01/good_times_with_bad_music_1050x700.jpg",
    owner:  owner ,
    title: "Music Time",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "music",
  },
  {
    id: 5,
    video:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Youth-soccer-indiana.jpg/640px-Youth-soccer-indiana.jpg",
    owner:  owner ,
    title: "Football as a soccer:)",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "sport",
  },
  {
    id: 6,
    video:
      "https://pbblogassets.s3.amazonaws.com/uploads/2015/03/header-image-337757.jpg",
    owner:  owner ,
    title: "Global Heating is truthy or...?",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "documentary",
  },
  {
    id: 7,
    video:
      "https://res.cloudinary.com/highereducation/image/upload/v1533591754/TheBestColleges.org/study-notebooks.jpg",
    owner:  owner ,
    title: "Learn is important for everyone",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "learn",
  },
  {
    id: 8,
    video:
      "https://learnenglish.britishcouncil.org/sites/podcasts/files/RS6053_dv029034-low.jpg",
    owner:  owner ,
    title: "Animals life in Safari",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "wild",
  },
  {
    id: 9,
    video:
      "https://www.forbes.com/advisor/wp-content/uploads/2021/03/traveling-based-on-fare-deals.jpg",
    owner: owner ,
    title: "Traveling around the world",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "travel",
  },
  {
    id: 10,
    video:
      "https://www.spinningclock.com/media/services-images/services-whatis-01.jpg",
    owner:  owner ,
    title: "Animation born in Japan?",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "Animation",
  },
  {
    id: 11,
    video:
      "https://storage-prtl-co.imgix.net/endor/articles/434/images/1663928047_shutterstock_2083362643.jpg?max-w=660&max-h=532&fit=crop&auto=format,compress&q=40",
    owner:  owner ,
    title: "Computer Science rising as fast as",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "cs",
  },
  {
    id: 12,
    video:
      "https://images.unsplash.com/photo-1515041219749-89347f83291a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FydG9vbnxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80",
    owner:  owner ,
    title: "Cartoon time",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "cartoon",
  },
  {
    id: 13,
    video:
      "https://m.media-amazon.com/images/M/MV5BMjYwODExNzUwMV5BMl5BanBnXkFtZTgwNTgwNjUyOTE@._V1_.jpg",
    owner:  owner ,
    title: "Movies for rest time",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "movie",
  },
  {
    id: 14,
    video:
      "https://nwc.edu/academics/photos/program-photos/computer-science.jpg",
    owner: owner ,
    title: "learning CS for your future...",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "cs",
  },
  {
    id: 15,
    video:
      "https://lingua-airlines.ru/wp-content/uploads/2017/01/annual-travel-insurance-plan-at-directasia.jpg",
    owner:  owner ,
    title: "Travel...",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "travel",
  },
  {
    id: 16,
    video:
      "https://www.columbiacollege.ca/wp-content/uploads/2019/05/Music.png",
    owner: owner,
    title: "I like to moved it ....",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "music",
  },
  {
    id: 17,
    video:
      "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/4f995dde6b43fbe45bab9336476a66df17cc83270f06bc5e73492d21edcf7bef._RI_TTW_.jpg",
    owner: owner ,
    title: "Kids time...",
    channel: "LOREM IPSUM",
    views: "1.6K views",
    dot: dot,
    time: "10 days ago",
    category: "cartoon",
  },
  {
    id: 18,
    video:
      "https://www.usmagazine.com/wp-content/uploads/1428049615_mcdsaha_ec188_h_the-fast-the-furious-zoom.jpg?crop=0px%2C215px%2C1280px%2C673px&resize=1200%2C630&quality=40&strip=all",
    owner:  owner ,
    title: "The new movie 2023",
    channel: "LOREM IPSUM",
    views: "1.4K views",
    dot: dot,
    time: "10 days ago",
    category: "movie",
  },
  {
    id: 19,
    video:
      "https://daily.jstor.org/wp-content/uploads/2023/01/good_times_with_bad_music_1050x700.jpg",
    owner:  owner ,
    title: "The Summer All Disco Dancing Musics",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "music",
  },
  {
    id: 20,
    video:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Youth-soccer-indiana.jpg/640px-Youth-soccer-indiana.jpg",
    owner:  owner ,
    title: "Sport for healthy life",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "sport",
  },
  {
    id: 21,
    video:
      "https://pbblogassets.s3.amazonaws.com/uploads/2015/03/header-image-337757.jpg",
    owner:  owner ,
    title: "National Geagraphic",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "documentary",
  },
  {
    id: 22,
    video:
      "https://res.cloudinary.com/highereducation/image/upload/v1533591754/TheBestColleges.org/study-notebooks.jpg",
    owner:  owner ,
    title: "Learning is important",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "learn",
  },
  {
    id: 23,
    video:
      "https://learnenglish.britishcouncil.org/sites/podcasts/files/RS6053_dv029034-low.jpg",
    owner:  owner ,
    title: "Wild Animals life in African Savannas",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "wild",
  },
  {
    id: 24,
    video:
      "https://www.forbes.com/advisor/wp-content/uploads/2021/03/traveling-based-on-fare-deals.jpg",
    owner: owner ,
    title: "Let's travelling with us",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "travel",
  },
  {
    id: 25,
    video:
      "https://www.spinningclock.com/media/services-images/services-whatis-01.jpg",
    owner:  owner ,
    title: "Animation about Kids",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "Animation",
  },
  {
    id: 26,
    video:
      "https://storage-prtl-co.imgix.net/endor/articles/434/images/1663928047_shutterstock_2083362643.jpg?max-w=660&max-h=532&fit=crop&auto=format,compress&q=40",
    owner:  owner ,
    title: "Computer Science interviews",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "cs",
  },
  {
    id: 27,
    video:
      "https://images.unsplash.com/photo-1515041219749-89347f83291a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FydG9vbnxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80",
    owner:  owner ,
    title: "Live cartoon channel",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "cartoon",
  },
  {
    id: 28,
    video:
      "https://m.media-amazon.com/images/M/MV5BMjYwODExNzUwMV5BMl5BanBnXkFtZTgwNTgwNjUyOTE@._V1_.jpg",
    owner:  owner ,
    title: "Mechanic",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "movie",
  },
  {
    id: 29,
    video:
      "https://nwc.edu/academics/photos/program-photos/computer-science.jpg",
    owner: owner ,
    title: "Computer...",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "cs",
  },
  {
    id: 30,
    video:
      "https://lingua-airlines.ru/wp-content/uploads/2017/01/annual-travel-insurance-plan-at-directasia.jpg",
    owner:  owner ,
    title: "Atlas Travel TV",
    channel: "LOREM IPSUM",
    views: "1.8K views views",
    dot: dot,
    time: "10 days ago",
    category: "travel",
  },
];
